name: Continuous integration

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        types: [ opened, synchronize ]

jobs:
    check:
        name: Code check
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        strategy:
            matrix:
                command: [ lint, typecheck, test ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v5

            -   name: Setup node
                uses: actions/setup-node@v6
                with:
                  node-version: 22

            -   name: Install dependencies
                run: npm install

            -   name: ${{ matrix.command }}
                run: npm run ${{ matrix.command }}
